### ISSUE TITLE
VVOL datastore

### ISSUE THREAD

**Issue by shyamachilles** [Infinidat/infi.pyvmomi_wrapper#4]
Hello ! 

Our test framework is python based, and to do VVOL testing, we use pyVmomi in our library.

My current task is to automate creating VVOL datastore. Could I please know if there is any API support to do the same?

**Comment by wiggin15** [comment]
Hi there!
I'm afraid I never created a VVol using the API, but I can give you some leads:
It looks like you can use [HostDatastoreSystem.CreateVvolDatastore](http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.DatastoreSystem.html#createVvolDatastore) to do what you want. This method accepts an object of type [HostDatastoreSystemVvolDatastoreSpec](http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.host.DatastoreSystem.VvolDatastoreSpec.html) which you need to fill out with an scId (storage container ID). I'm not entirely sure how to get the container ID, but you can use the SMS method [QueryStorageContainer](https://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.smssdk.doc/sms.StorageManager.html#queryStorageContainer), which returns [StorageContainerResult](https://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.wssdk.smssdk.doc%2Fsms.storage.StorageContainerResult.html). This result contains storageContainer objects, each of which have a name attribute - this may be the ID but I don't know.

infi.pyvmomi_wrapper can help you get easy access to the host datastore system and to the SMS APIs.
Here's something that _may_ work, but I don't promise because I don't have access to a VVol-capable array:

``` python
from pyVmomi import vim
from infi.pyvmomi_wrapper import Client
from infi.pyvmomi_wrapper.sms import SmsClient

# fill out the server/username/password
client = Client("vcenter", "user", "password")
sms = SmsClient(client)
sm = sms.service_instance.QueryStorageManager()
# this will work only on vSphere 6
container_result = sm.QueryStorageContainer()
# find the relevant container. Here I'm taking the first one
container = container_result.storageContainer[0]
# name is the ID? maybe not
scid = container.containerId

vvol_spec = vim.HostDatastoreSystemVvolDatastoreSpec(name="vvolds", scId=scid)

# find the ESX host you want to create the datastore for. Here I'm taking the first one
host = client.get_host_systems()[0]
# datastore creation
new_datastore = host.configManager.datastoreSystem.CreateVvolDatastore(vvol_spec)
```

**Comment by NiranjanSardeshpande** [comment]
from pyVmomi import vim, sms
from pyVim.connect import SoapStubAdapter
from pyVim.connect import SmartConnect, Disconnect
import time

class SmsClient(object):
    def **init**(self, client):
        import re
        session_cookie = re.search('vmware_soap_session="(.*?)"', client.service_instance._stub.cookie).group(1)
        additional_headers = {'vcSessionCookie': session_cookie}
        #stub = SoapStubAdapter(client.host, path="/sms/sdk", version="sms.version.version2", requestContext=additional_headers)
        stub = SoapStubAdapter(client.host, path="/sms/sdk", version="sms.version.version1", requestContext=additional_headers)
        self.service_instance = sms.ServiceInstance("ServiceInstance", stub)

class Client(object):
    def **init**(self, vcenter_address, username=None, password=None, certfile=None, keyfile=None, sslContext=None):
        import ssl
        context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
        context.verify_mode = ssl.CERT_NONE
        server_name = "vcenter-group2.cxo.storage.hpecorp.net"
        vuser = 'administrator@vsphere.local'
        vpass = 'Admin!23'
        self.service_instance = SmartConnect(host=server_name, user=vuser, pwd=vpass, sslContext=context)
        self.service_content = self.service_instance.content
        self.session_manager = self.service_content.sessionManager
        self.root = self.service_content.rootFolder
        self.host = vcenter_address
        self.property_collectors = {}

# first open a "regular" client

client = Client("c3-dl360pg8-100-vm01.cxo.storage.hpecorp.net", username="administrator@vsphere.local", password="Admin!23")

sms_client = SmsClient(client)
storage_manager = sms_client.service_instance.QueryStorageManager()
storage_providers = storage_manager.QueryProvider()

Hello the above is my code and getting a error when I try to execute it as below :- 
[root@c3-dl360pg8-110 infi.pyvmomi_wrapper-develop]# python testsms.py
Traceback (most recent call last):
  File "testsms.py", line 36, in <module>
    storage_manager = sms_client.service_instance.QueryStorageManager()
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 575, in <lambda>
    self.f(_(self.args + (obj,) + args), *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 381, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1318, in InvokeMethod
    req = self.SerializeRequest(mo, info, args)
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 894, in SerializeRequest
    method=info.name)
pyVmomi.VmomiSupport.MethodNotFound: (vmodl.fault.MethodNotFound) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = <unset>,
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   receiver = 'sms.ServiceInstance:ServiceInstance',
   method = 'QueryStorageManager'
}

Any help would be appreciated.

**Comment by wiggin15** [comment]
Hi. You're getting this error because the SMS client is using the older SMS API version (4). QueryStorageContainer was added in vSphere 6 which is SMS API version 5. I just committed a fix to support changing the API version.

Please check out the latest 'develop' branch of infi.pyvmomi_wrapper, and in the code from above, amend this line:
`sms = SmsClient(client)`
to this:
`sms = SmsClient(client, version="version5")`
Let me know if it works.

**Comment by NiranjanSardeshpande** [comment]
oops I forgot to mention I was also getting below error message ...
[root@c3-dl360pg8-110 infi.pyvmomi_wrapper-develop]# python test.py
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    from infi.pyvmomi_wrapper.sms import SmsClient
  File "/usr/local/lib/python2.7/site-packages/infi/pyvmomi_wrapper/sms/**init**.py", line 1, in <module>
    import SmsObjects
  File "/usr/local/lib/python2.7/site-packages/infi/pyvmomi_wrapper/sms/SmsObjects.py", line 152, in <module>
    CreateManagedType("sms.ServiceInstance", "SmsServiceInstance", "vmodl.ManagedObject", "sms.version.version1", None, [("queryStorageManager", "QueryStorageManager", "sms.version.version2", (), (0, "sms.StorageManager", "sms.StorageManager"), "StorageViews.View", None), ("querySessionManager", "QuerySessionManager", "sms.version.version5", (), (0, "sms.auth.SessionManager", "sms.auth.SessionManager"), "System.Anonymous", None), ("queryAboutInfo", "QueryAboutInfo", "sms.version.version2", (), (0, "sms.AboutInfo", "sms.AboutInfo"), "StorageViews.View", None)])
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 751, in CreateManagedType
    _SetWsdlMethod(typeNs, meth[1], dic)
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 1191, in _SetWsdlMethod
    (ns, wsdlName, inputMM[0], curMM[0]))
RuntimeError: Duplicate wsdl method urn:sms QueryStorageManager (new class sms.ServiceInstance vs existing sms.ServiceInstance)

**Comment by NiranjanSardeshpande** [comment]
[root@c3-dl360pg8-110 infi.pyvmomi_wrapper-develop]# python testsms.py
Traceback (most recent call last):
  File "testsms.py", line 36, in <module>
    storage_manager = sms_client.service_instance.QueryStorageManager()
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 575, in <lambda>
    self.f(_(self.args + (obj,) + args), *_kwargs)
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 381, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1323, in InvokeMethod
    conn.request('POST', self.path, req, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/local/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/local/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/local/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/ssl.py", line 579, in __init__
    self.do_handshake()
  File "/usr/local/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

**Comment by NiranjanSardeshpande** [comment]
[root@c3-dl360pg8-110 infi.pyvmomi_wrapper-develop]# cat testsms.py
from pyVmomi import vim, sms
from pyVim.connect import SoapStubAdapter
from pyVim.connect import SmartConnect, Disconnect
import time

class SmsClient(object):
    def **init**(self, client, version="version4"):
        import re
        # https://github.com/vmware/pyvmomi/pull/165#issuecomment-213623822
        session_cookie = client.service_instance._GetStub().cookie.split('"')[1]
        additional_headers = {'vcSessionCookie': session_cookie}
        stub = SoapStubAdapter(client.host, path="/sms/sdk", version="sms.version." + version,requestContext=additional_headers)
        self.service_instance = sms.ServiceInstance("ServiceInstance", stub)

class Client(object):
    def **init**(self, vcenter_address, username=None, password=None, certfile=None, keyfile=None, sslContext=None):
        import ssl
        context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)
        context.verify_mode = ssl.CERT_NONE
        server_name = "vcenter-group2.cxo.storage.hpecorp.net"
        vuser = 'administrator@vsphere.local'
        vpass = 'Admin!23'
        self.service_instance = SmartConnect(host=server_name, user=vuser, pwd=vpass, sslContext=context)
        self.service_content = self.service_instance.content
        self.session_manager = self.service_content.sessionManager
        self.root = self.service_content.rootFolder
        self.host = vcenter_address
        self.property_collectors = {}

# first open a "regular" client

client = Client("c3-dl360pg8-100-vm01.cxo.storage.hpecorp.net", username="administrator@vsphere.local", password="Admin!23")

sms_client = SmsClient(client,version="version5")
storage_manager = sms_client.service_instance.QueryStorageManager()
storage_providers = storage_manager.QueryProvider()

**Comment by wiggin15** [comment]
Hi @NiranjanSardeshpande.
1. It's difficult to read your code and the exceptions because of the formatting. Please read the Github documentation regarding [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) and use the Preview feature to make sure you are posting the code correctly.
2. I'm not sure if you are using the latest code from the repository. The file infi/pyvmomi_wrapper/sms/SmsObjects.py was deleted recently so I think you are still using an older version of the code. You should also use the latest version of pyvmomi to make the code work. There were recent changes to both codebases that are required for using SMS.
3. It looks like you are using a mix of code from pyvmomi and from infi.pyvmomi_wrapper instead of the snippet I provided. I don't know if I can debug your code for you. Also, like I said, I am myself unsure how to create a vvol so I'm afraid I can't guide you all the way.

**Comment by NiranjanSardeshpande** [comment]
Hey apologies wiggin15 for the inconvenience caused to you.I could finally make it work see below. Thanks a lot for your time and patience. You can close this now.

[root@c3-dl360pg8-110 infi.pyvmomi_wrapper-develop]# python testsms.py
'sms.StorageManager:storageManager'
(sms.provider.Provider) [
   'sms.provider.VasaProvider:vasaProvider-7',
   'sms.provider.VasaProvider:vasaProvider-8'
]
[root@c3-dl360pg8-110 infi.pyvmomi_wrapper-develop]#

**Comment by praveenkumarudatha17** [comment]
Can you please tell me after getting the storage providers, how we can create vvol datastore
